### ISSUE TITLE
SNR Computation

### ISSUE THREAD

**Issue by jnoelvictorino** [Satishpas2/Speech-Separation#1]
In `Making_list_for_mixture_like_wsj-matlab-Hindi.py`
SNR is computed using this formula:
`snr_1 = float(decimal.Decimal(random.randrange(1, 250))/100)`
May I ask how did you come up with this? And how does this translate into dB?

**Comment by Satishpas2** [comment]
snr_1 and snr_2 is just to make the list like this....
[mixhin_2_spk_tt.txt](https://github.com/Satishpas2/Speech-Separation/files/4169507/mixhin_2_spk_tt.txt)
And these values in this file will be further utilized in other scripts.

**Comment by jnoelvictorino** [comment]
Thank you for the quick response.
I understand that the same list is needed by create_mixture script from MERL.
I will ask them how does this translate to their claim of 0 dB - 5 dB.
I am after how did the compute that mixing ratio in decibels.

In any case, thank you for your work! I am using it for other language data, as well.
